// <auto-generated />
namespace RoomMate.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_address_postCode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_address_postCode));
        
        string IMigrationMetadata.Id
        {
            get { return "202012042202504_add_address_postCode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
